### ISSUE TITLE
tworzenie korpusu

### ISSUE THREAD

**Issue by ewa1952** [nathell/smyrna#1]
Stworzylam korpus pod nazwą wychowanie -  system pokazal, że jest  365 dokumentow,
ale jak chcialam je przeszukać, otrzymuę informacje,że system niczego nie znalazł
Nie wiem, jak mam stworzy i przejrzeć korpsu dokumentow do konkretnego lesemu

**Comment by nathell** [comment]
Zamykam ze względu na pojawienie się nowej wersji.
